# On définie les cibles pour lunch en user, engineering et userdebug
add_lunch_combo lo52_BayoudeIzoukaYosef_kammounyessine-eng
add_lunch_combo lo52_BayoudeIzoukaYosef_kammounyessine-user
add_lunch_combo lo52_BayoudeIzoukaYosef_kammounyessine-userdebug