# Define targett for lunch (eng, user, userdebug)
add_lunch_combo lo52_BayoudeIzoukaYosef_kammounyessine-eng
add_lunch_combo lo52_BayoudeIzoukaYosef_kammounyessine-user
add_lunch_combo lo52_BayoudeIzoukaYosef_kammounyessine-userdebug
